config/routes.rb
Rails.application.routes.draw do
  resources :offices
  # devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "/about", to: "pages#about"

  get "/services", to: "pages#services"

  get "/overview", to: "pages#overview"

  get "/checklist", to: "pages#checklist"

  get "/apply", to: "pages#apply"

  get "/contact", to: "pages#contact"

  get "/offices", to: "pages#offices"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/office.rb
class Office < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  before_action :set_office, only: %i[show edit update destroy]

  # GET /offices
  def index
    @offices = Office.all

    @markers = @offices.geocoded.map do |office|
      {
        lat: office.latitude,
        lng: office.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {office: office})
      }
    end
  end

  # GET /offices/1
  def show
  end

  # GET /offices/new
  def new
    @office = Office.new
  end

  # GET /offices/1/edit
  def edit
  end

  # POST /offices
  def create
    @office = Office.new(office_params)

    if @office.save
      redirect_to @office, notice: "Office was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /offices/1
  def update
    if @office.update(office_params)
      redirect_to @office, notice: "Office was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /offices/1
  def destroy
    @office.destroy
    redirect_to offices_url, notice: "Office was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_office
      @office = Office.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def office_params
      params.require(:office).permit(:name, :address)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def services
  end

  def overview
  end

  def checklist
  end

  def apply
  end

  def contact
  end

  def office
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Janek Services</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "/assets/application.js", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body><%= render "shared/navbar" %>
  <%= render "shared/flashes" %>
    <%= yield %>
  <%= render "shared/footer" %>
  </body>
</html>

app/views/offices/_form.html.erb
<%= simple_form_for(@office) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/offices/_info_window.html.erb
<h2><%= office.name %></h2>
<p><%= office.address %></p>

app/views/offices/_office.html.erb
<div id="<%= dom_id office %>">
  <p>
    <strong>Name:</strong>
    <%= office.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= office.address %>
  </p>

</div>

app/views/offices/edit.html.erb
<h1>Editing office</h1>

<%= render "form", office: @office %>

<br>

<div>
  <%= link_to "Show this office", @office %> |
  <%= link_to "Back to offices", offices_path %>
</div>

app/views/offices/index.html.erb
<h1>Our Office</h1>

<div id="offices">
  <% @offices.each do |office| %>
    <%= render office %>
   <% end %>
</div>



<div class="office-map"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/offices/new.html.erb
<h1>New office</h1>

<%= render "form", office: @office %>

<br>

<div>
  <%= link_to "Back to offices", offices_path %>
</div>

app/views/offices/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @office %>

<div>
  <%= link_to "Edit this office", edit_office_path(@office) %> |
  <%= link_to "Back to offices", offices_path %>

  <%= button_to "Destroy this office", @office, method: :delete %>
</div>

app/views/pages/about.html.erb
<body class="bg-all">

<div class="services-banner", style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dtxhgfzpd/image/upload/v1680011380/janek/banner_ut5vhe.jpg);">
 <div class="container">
    <div>
        <h1>We are Janek Services</h1>
    </div>
  </div>
  </div>

<div class="container">
  <div class="row d-flex justify-content-around">
  <hr>
    <div class="col-4 about-us">
        <h4>Janek Services is a stagehand company based in Kansas City, Missouri.
        For over 30 years, we have contributed to production and stage builds across the country.
        Experienced and detail-oriented, our crews provide staffing solutions to a diverse range of clients.</h4>
    </div>
      <div class="col-4 d-flex justify-content-end">
        <div id="carouselSlides" class="carousel-slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <%= image_tag "stage1.png", alt: "stage 1", width: 400, height: 225%>
            </div>
            <div class="carousel-item">
              <%= image_tag "stage2.png", alt: "stage 2", width: 400, height: 225%>
            </div>
            <div class="carousel-item">
              <%= image_tag "stage3.png", alt: "stage 3", width: 400, height: 225%>
            </div>
            <div class="carousel-item">
              <%= image_tag "stage4.png", alt: "stage 4", width: 400, height: 225%>
            </div>
            <div class="carousel-item">
              <%= image_tag "stage5.png", alt: "stage 5", width: 400, height: 225%>
            </div>
            <div class="carousel-item">
              <%= image_tag "stage6.png", alt: "stage 6", width: 400, height: 225%>
            </div>
            <div class="carousel-item">
              <%= image_tag "stage_nfl.jpg", alt: "stage 7", width: 400, height: 225%>
            </div>
          </div>
        </div>
        </div>

      <script>
          var myCarousel = 0;
          carousel();

          function carousel() {
            var i;
            var x = document.getElementsByClassName("carousel-item");
            for (i = 0; i < x.length; i++) {
              x[i].style.display = "none";
            }
            myCarousel++;
            if (myCarousel > x.length) {myCarousel = 1}
            x[myCarousel-1].style.display = "flex";
            setTimeout(carousel, 4000);
          }
          </script>
    </div>
    <hr>
  </div>
</div>


<div class="container fluid mt-5 list-box">
  <div class="row justify-content-center">
    <div class="col-6">
      <h3 class="list-title">Event Support</h3>
      <ul>
        <li>Concerts</li>
        <li>Conventions</li>
        <li>Festivals</li>
        <li>Theater</li>
        <li>Trade Shows</li>
        <li>Corporate Meetings</li>
        <li>General Labor</li>
      </ul>
    </div>

    <div class="col-6">
       <h3 class="list-title">Staffing Solutions</h3>
       <ul>
        <li>Stagehands</li>
        <li>Audio/Video Technicians</li>
        <li>Lighting Technicians</li>
        <li>Labor/Loaders</li>
        <li>Riggers</li>
        <li>Spotlight Operators</li>
        <li>Forklift Drivers</li>
      </ul>
    </div>
  </div>
  </div>

  <div class="interest">
    <h3>Interested?</h3>
    <div class="link-info">
    <a class="btn btn-secondary btn-style" href="/overview">Learn More</a>
    <a class="btn btn-secondary btn-style" href="/apply">Apply Now</a>
    </div>
  </div>

</div>

</body>

app/views/pages/apply.html.erb
<body class="apply-background">
<div class="container fluid mt-5 apply-box">
  <div class="row justify-content-center">
      <h3>Janek Services is an "At Will" Equal Opportunity Employer</h3>
      <h5><strong>BEFORE PROCEEDING</strong> - You must be 18 years of age or older,
      have a high school diploma or GED, a working phone and your own car. Applicants
      not meeting this basic criteria will not be considered for employment.</h5>
      <h5>Please fill the fields below and click submit. You must fill in all required fields
      in order to submit your application.</h5>
  </div>
  </div>
  <div class="container fluid mt-3">
    <div class="row justify-content-center">
      <div class="apply-form border border-secondary">
        <h4 class="questions header">Contact Information</h4>
        <form>
          <div class="mb-3">
            <input type="name" class="form-control" placeholder="Full Name">
          </div>
          <div class="mb-3">
            <input type="email" class="form-control" placeholder="Email Address">
          </div>
          <div class="mb-3">
            <input type="address" class="form-control" placeholder="Street Address">
          </div>
          <div class="mb-3">
            <input type="phone" class="form-control" placeholder="Cell Phone">
          </div>
          <div class="mb-3">
            <input type="phone" class="form-control" placeholder="Other Phone">
          </div>
          <div class="mb-3">
            <input type="learn" class="form-control" placeholder="How did you learn about us?">
          </div>
           <h5 class="questions">Are you lawfully permitted to work in the USA?</h5>
          <div class="form-check form-check-inline">
              <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1">
              <label class="form-check-label" for="flexRadioDefault1">
                Yes
              </label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2">
            <label class="form-check-label" for="flexRadioDefault2">
              No
            </label>
          </div>
          <h6>Proof of citizenship or immigration status will be required upon employment.</h6>
          <h5 class="questions">What type of work are you looking for?</h5>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
            <label class="form-check-label" for="flexCheckDefault">
              Days
            </label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
            <label class="form-check-label" for="flexCheckChecked">
              Evenings
            </label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
            <label class="form-check-label" for="flexCheckDefault">
              Weekends
            </label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
            <label class="form-check-label" for="flexCheckChecked">
              On Call
            </label>
          </div>
          <div class="mb-3">
            <label for="how" class="form-label">From what date are you available to work?</label>
            <input type="learn" class="form-control" placeholder="Availability">
          </div>
          <h4 class="questions header">Education</h4>
            <h5 class="questions">High School Diploma or GED?</h5>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1">
            <label class="form-check-label" for="flexRadioDefault1">
              Yes
            </label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked>
            <label class="form-check-label" for="flexRadioDefault2">
              No
            </label>
          </div>
          <div class="mb-3">
            <input type="learn" class="form-control" placeholder="High School Attended">
          </div>
          <div class="mb-3">
            <input type="learn" class="form-control" placeholder="Date of Diploma/GED (mm/dd/yyyy)">
          </div>
          <div class="mb-3">
            <input type="learn" class="form-control" placeholder="Technical/Busines/Other Institution Attended">
          </div>
          <div class="mb-3">
            <input type="learn" class="form-control" placeholder="Technical/Busines/Other dates attended (mm/dd/yyyy)">
          </div>
          <div class="mb-3">
            <input type="learn" class="form-control" placeholder="Technical/Busines/Other Courses or Degree">
          </div>
          <div class="mb-3">
            <textarea class="form-control" rows="5" placeholder="Please describe other skills, training, honors, or extracurricular activities you feel might be relevant to the position for which you are applying."></textarea>
          </div>
            <h4 class="questions header">Miscellaneous</h4>
              <h5 class="questions">Have you ever worked for or applied to Janek Services in the past?</h5>
               <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1">
                <label class="form-check-label" for="flexRadioDefault1">
                  No
                </label>
               </div>
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked>
                <label class="form-check-label" for="flexRadioDefault2">
                  Applied
                </label>
              </div>
               <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked>
                <label class="form-check-label" for="flexRadioDefault2">
                  Employed
                </label>
              </div>
              <div class="mb-3">
                <label for="Undergrad" class="form-label">If yes, when and for what position?</label>
                <input type="learn" class="form-control" placeholder="Date Applied">
              </div>
              <div>
                <input type="learn" class="form-control" placeholder="Position">
              </div>
              <div class="mb-3">
               <label for="other" class="form-label"></label>
               <textarea class="form-control" rows="5" placeholder="Please list any relatives or close contacts who currently work for Janek Services."></textarea>
              </div>

             <h4 class="questions header">Employment</h4>
             <h5 class="questions">List your current or most recent employer. Resumés may be submitted to supplement the information requested on this application.</h5>
             <h5 class="questions">Employer</h5>
             <div class="mb-3">
                <label for="employment" class="form-label"></label>
                <input type="learn" class="form-control" placeholder="Position Title">
             </div>
              <div class="mb-3">
                <input type="learn" class="form-control" placeholder="Start Date">
              </div>
             <div class="mb-3">
                <input type="learn" class="form-control" placeholder="End Date">
              </div>
              <p>Employment Type:</p>
             <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1">
                <label class="form-check-label" for="flexRadioDefault1">
                  Full-time
                </label>
               </div>
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked>
                <label class="form-check-label" for="flexRadioDefault2">
                  Part-time
                </label>
              </div>
              <div class="mb-3">
                <input type="learn" class="form-control" placeholder="If part time, hours per week">
              </div>
              <div class="mb-3">
                <input type="learn" class="form-control" placeholder="Employer">
              </div>
              <div class="mb-3">
                <input type="learn" class="form-control" placeholder="Address">
              </div>
              <div class="mb-3">
                <input type="learn" class="form-control" placeholder="Phone">
              </div>
              <div class="mb-3">
                <input type="learn" class="form-control" placeholder="Supervisor Name">
              </div>
              <div class="mb-3">
                <label for="other" class="form-label"></label>
                <textarea class="form-control" rows="3" placeholder="Position Duties"></textarea>
              </div>
              <div class="mb-3">
                <label for="other" class="form-label"></label>
                <textarea class="form-control" rows="3" placeholder="Reason for Leaving"></textarea>
              </div>

            <h4 class="questions header">PLEASE READ CAREFULLY:</h4>
            <p>I certify that my answers are true and complete to the best of my knowledge. I authorize Janek Services to make inquiries concerning my personal character including my employment record. If this application leads to employment, I understand that any misrepresentation, omissions of facts or incomplete answers in any application document will disqualify me from further consideration for employment and that, if employed, any misrepresentation or omissions of facts in any application document will be cause for my immediate dismissal.

              <br>
              I understand that if I am hired, my work hours are subject to change, my employment is for no definite period of time, and may, regardless of the date of payment of my wages, be terminated at any time without cause or any prior notice. I further understand that no oral promise, employer policy, customer business practice or other procedure constitute an employment contract or modification of the at-will employment relationship between me and the employer.
              I also understand that as required by Federal law, if hired, I will be required to furnish documentation establishing my identity, eligibility to work and residency.</p>

              <div class="mb-3">
                <input type="learn" class="form-control" placeholder="Application Date">
              </div>
              <div class="mb-3">
                <input type="learn" class="form-control" placeholder="Please Type Your Name">
              </div>
              <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">
                  By checking this box, I indicate that I understand and agree to the above statements.
                </label>
              </div>


          <button type="submit" class="btn btn-secondary btn-style">Submit Application</button>
        </form>
      </div>
      </div>
      </div>
</body>

app/views/pages/checklist.html.erb
<body class="bg-all">

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),
  url(https://res.cloudinary.com/dtxhgfzpd/image/upload/v1680011380/janek/banner_ut5vhe.jpg);">
  <div class="container">
    <h1>Stagehand Checklist</h1>
  </div>
</div>

<div class="container mt-5">
  <div class="text-center">
    <h3>Tools and Safety Equipment for the Job</h3>
  </div>
  <div class="container fluid mt-3 checklist-box">
  <div class="row justify-content-center">

    <div class="col-4 checklist">
      <h5>Required</h5>
      <div>
        <i class="fa-solid fa-check"></i>
        <span class="checklist-item">Work Gloves</span>
      </div>
      <div>
        <i class="fa-solid fa-check"></i>
        <span class="checklist-item">Steel Toed Boots</span>
      </div>
      <div>
        <i class="fa-solid fa-check"></i>
        <span class="checklist-item">8" Crescent Wrench</span>
      </div>
    </div>
    <div class="col-4 checklist">
      <h5>Highly Recommended</h5>
        <div>
        <i class="fa-solid fa-check"></i>
        <span class="checklist-item">Pocket Knife</span>
      </div>
      <div>
        <i class="fa-solid fa-check"></i>
        <span class="checklist-item">Flashlight</span>
      </div>
      <div>
        <i class="fa-solid fa-check"></i>
        <span class="checklist-item">Hammer</span>
      </div>
      <div>
        <i class="fa-solid fa-check"></i>
        <span class="checklist-item">Electrical Tape</span>
      </div>
    </div>
    <div class="col-3 checklist">
      <h5>Loaners Available Upon Request</h5>
    <div>
      <i class="fa-solid fa-check"></i>
      <span class="checklist-item">Hard Hats</span>
    </div>
    <div>
      <i class="fa-solid fa-check"></i>
      <span class="checklist-item">Hi-Vis Vests</span>
    </div>
          <p>All equipment is collected after work is completed.</p>
  </div>
  </div>
  </div>
</div>
</body>

app/views/pages/contact.html.erb
<body class="bg-city">

<div class="container" style="padding-top: 100px">
<div class="row">
<div class="col-6">
   <h2 class="title">Contact Us</h2>
      <div class="contact-form border border-secondary">

        <form>
          <div class="mb-3">
            <label for="fullname" class="form-label">Full Name</label>
            <input type="name" class="form-control" placeholder="Name">
          </div>
          <div class="mb-3">
            <label for="phone-number" class="form-label">Phone</label>
            <input type="phone" class="form-control" placeholder="Phone">
          </div>
          <div class="mb-3">
            <label for="email" class="form-label">Email Address</label>
            <input type="email" class="form-control" placeholder="Email">
          </div>
          <div class="mb-3">
            <label for="email" class="form-label">Questions/Comments?</label>
            <textarea class="form-control" rows="5" placeholder="Tell us how we can help"></textarea>
          </div>
          <button type="submit" class="btn btn-secondary btn-style">Submit</button>
        </form>
      </div>
      </div>

      <div class="col-6">

        <h2 class="title">Directory</h2>

        <div class="contact-info border border-secondary">
        <h4>Bryant Kincaid</h4>
        <h5>General Manager</h5>
        <h5><%= mail_to 'bryant@janekservices.com' %></h5>
        </div>

        <div class="contact-info border border-secondary">
        <h4>Heath Cox</h5>
        <h5>Director of Business Development</h5>
        <h5><%= mail_to 'heath@janekservices.com' %></h5>
        </div>

        <div class="contact-info border border-secondary">
        <h4>Donna Stacy</h4>
        <h5>HR Director</h5>
        <h5><%= mail_to 'donna@janekservices.com' %></h5>
        </div>
      </div>
  </div>
</div>

</body>

app/views/pages/home.html.erb
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>


<html>

<body class="bg-all">


<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),
    url(https://res.cloudinary.com/dtxhgfzpd/image/upload/v1680011380/janek/banner_ut5vhe.jpg);">
  <div class="container">
    <h1>JANEK SERVICES</h1>
    <p>4050 Pennsylvania Ave., Suite 111 <br>
      Kansas City, Missouri 64111</p>
  </div>
</div>


<div class="container overview" style="text-align:center">
  <h2>We Make Events Happen</h2>
  <h4>Experienced Stagehands for Hire</h4>
  <p> At Janek Services, our mission is to provide an organized crew of skilled workers for your event.
  Our production teams are ready to meet your objectives and exceed your expectations.
  We stand behind our team, training, and services to best suit our client's needs.
  Catering to diverse events of all sizes, our clients are in experienced hands.</p>
  <hr>
</div>

<div class="container">
<div class="cards">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dtxhgfzpd/image/upload/v1680011208/janek/card1_setpwl.jpg)">
    <%= link_to "About Us", about_path, class:  "btn btn-secondary btn-style" %>
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dtxhgfzpd/image/upload/v1680010738/janek/card2_z9lm5m.jpg)">
      <%= link_to "Contact Us", contact_path, class:  "btn btn-secondary btn-style" %>
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dtxhgfzpd/image/upload/v1680010737/janek/card3_frvjyx.jpg)">
    <%= link_to "Join Our Crew", apply_path, class: "btn btn-secondary btn-style" %>
  </div>
</div>

</div>

</body>

</html>

app/views/pages/who-are-we.html.erb
<h1>Hello World</h1>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-info d-flex justify-content-evenly">
    <div>
      <h6>Phone</h6>
      <p>816-756-3296</p>
    </div>
    <div>
      <h6>Address</h6>
      <p>4050 Pennsylvania Ave., Suite 111 <br>
      Kansas City, Missouri 64111</p>
    </div>
    <div>
      <h6>Office Hours</h6>
      <p>Monday - Friday <br>
      9:00am - 5:00pm</p>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-md navbar-light navbar-style">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
           <li class="nav-item">
            <%= link_to "About Us", about_path, class: "nav-link" %>
          </li>
           <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Job Details
            </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Overview & Qualifications", overview_path, class: "nav-link" %></li>
                <li><%= link_to "Apply Now", apply_path, class: "nav-link" %></li>
              </ul>
            </li>
          <li class="nav-item">
              <%= link_to "Contact Us", contact_path, class: "nav-link"%>
          </li>

            <%# <ul class="dropdown-menu">
              <li><%= link_to "Contact Us", contact_path, class: "nav-link"</li> %>
              <%# <li><%= link_to "Office Info", offices_path, class: "nav-link"</li> %>
            <%# </ul>%>
          <%# </li> %>
      </ul>
   </div>
  </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>